baseURL: "https://complex2math.com"
languageCode: "en-us"
title: "Homepage of Complex2-Liu"
enableGitInfo: true

markup:
  highlight:
    lineNumbersInTable: false
    style: xcode
    linenos: true

taxonomies:
  category: categories
  tag: tags

permalinks:
  blog: /:section/:year/:month/:title/

menu:
  main:
  - identifier: about
    pre: '<i class="fas fa-home"></i>'
    name: About
    url: /
    weight: 1

  - identifier: blog
    name: Blog
    pre: '<i class="fas fa-blog"></i>'
    url: /blog/
    weight: 2


  - identifier: links
    name: Links
    pre: '<i class="fas fa-link"></i>'
    url: /links
    weight: 3
    parent: about

